### ISSUE TITLE
UItableview scrolling not smooth

### ISSUE THREAD

**Issue by SalmanAhmedDev** [weijentu/automatic-height-tagcells#11]
Hi,

You done a grade work but i m facing small issue when i increase records with around 25 tags Tableview scrolling not smooth and  some jerky. 

Thanks

**Comment by weijentu** [comment]
Hi @SalmanAhmedDev, do you mean 25 tags in one cell, or 25 tags total in one table?

**Comment by SalmanAhmedDev** [comment]
Yes boss

**Comment by SalmanAhmedDev** [comment]
25 tag in one cell

**Comment by SalmanAhmedDev** [comment]
here is small video : https://files.fm/u/gr7qstet

**Comment by weijentu** [comment]
I see. I think the issue comes from a bad estimation of the cell height. If you set 376.5 as estimated height, you will see the improvement. Or if all cells have the same count of tags and more than 25 in total, the issue will be gone. 

I suggest you can take a look of this post: [Jerky Scrolling After Updating UITableViewCell in place with UITableViewAutomaticDimension](https://stackoverflow.com/questions/27996438/jerky-scrolling-after-updating-uitableviewcell-in-place-with-uitableviewautomati) 

Cheers,

**Comment by SalmanAhmedDev** [comment]
Ok will update you. Thanks for your time

**Comment by SalmanAhmedDev** [comment]
i have run simulator its working fin but when i run device OS 10.0.2, Still scrolling  issues :( here is video  link : https://streamable.com/d8r7r

**Comment by SalmanAhmedDev** [comment]
@weijentu have you check video?

**Comment by weijentu** [comment]
Yeah, my suggestion is to increase estimate height if you have many cells with larger height.

**Comment by SalmanAhmedDev** [comment]
Yup i have increased to 400, but still not solved :(

**Comment by weijentu** [comment]
Hmm, it's probably owing to auto layout is a mechanism for dynamic size change at runtime; therefore, some sacrifice for performance might be unavoidable.
